<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="gripper">
  <!-- Command to run:
  rosrun xacro xacro.py gripper.xacro > gripper.urdf; roslaunch urdf_tutorial display.launch model:=gripper.urdf gui:=True
  -->
  
  <!-- Materials -->
  <xacro:macro name="material_metal">
  <material name="Metal">
    <color rgba="0.8 0.78 0.83 1.0" />
  </material>
  </xacro:macro>
  <xacro:macro name="material_darkmetal">
  <material name="Darkmetal">
    <color rgba="0.5 0.49 0.56 1.0" />
  </material>
  </xacro:macro>
  
  <!-- Variables -->
  <xacro:property name="base_finger_length" value="0.056" />
  <xacro:property name="top_finger_length" value="0.046" />
  <xacro:property name="base_finger_min" value="-0.785" />
  <xacro:property name="base_finger_max" value="0.087" />
  <xacro:property name="top_finger_min" value="1.431" />
  <xacro:property name="top_finger_max" value="0.489" />
  
  <!-- Finger macro -->
  <xacro:macro name="finger" params="name base x y z roll pitch yaw">
  <link name="${name}_finger_base">
    <visual>
      <origin xyz="0 ${base_finger_length/2} 0" rpy="0 0 0" />
      <geometry>
	<box size="0.007 ${base_finger_length} 0.014" rpy="0 0 0" />
      </geometry>
      <xacro:material_darkmetal />
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<cylinder length="0.014" radius="0.0035" />
      </geometry>
      <xacro:material_darkmetal />
    </visual>
  </link>
  <link name="${name}_finger_top">
    <visual>
      <origin xyz="0 ${top_finger_length/2} 0" rpy="0 0 0" />
      <geometry>
        <box size="0.007 ${top_finger_length} 0.014" />
      </geometry>
      <xacro:material_darkmetal />
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<cylinder length="0.014" radius="0.0035" />
      </geometry>
      <xacro:material_darkmetal />
    </visual>
  </link>
  <joint name="${name}_finger_basejoint" type="revolute">
    <parent link="${base}" />
    <child link="${name}_finger_base" />
    <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}" />
    <limit effort="1000.0" lower="${base_finger_min}" upper="${base_finger_max}" velocity="0.5"/>
    <axis xyz="0 0 1" />
  </joint>
  <joint name="${name}_finger_topjoint" type="revolute">
    <parent link="${name}_finger_base" />
    <child link="${name}_finger_top" />
    <axis xyz="0 0 1" />
    <origin xyz="0 ${base_finger_length} 0" rpy="0 0 0" />
    <limit effort="1000.0" lower="${top_finger_min}" upper="${top_finger_max}" velocity="0.5"/>
  </joint>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.056 0.040 0.065" rpy="0 0 0" />
      </geometry>
      <xacro:material_metal />
    </visual>
  </link>
  
  <!-- Create 3 fingers -->
  <xacro:finger name="f1" base="base_link" x="0.028" y="0.020" z="0" roll="0" pitch="0" yaw="0" />
  <xacro:finger name="f2" base="base_link" x="-0.028" y="0.020" z="0.019" roll="0" pitch="3.14" yaw="0" />
  <xacro:finger name="f3" base="base_link" x="-0.028" y="0.020" z="-0.019" roll="0" pitch="3.14" yaw="0" />
  
</robot>
